apiVersion: skaffold/v1beta13
kind: Config
metadata:
  name: bc-cloud
build:
  local:
    push: false
  artifacts:
    - image: bcc/api-server
      context: ./bcc-api-server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
    - image: bcc/job-worker
      context: ./bcc-job-worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
    # - image: bcc/web-client
    #   context: ./bcc-web-client
    #   docker:
    #     dockerfile: Dockerfile.dev
    #   sync:
    #     infer:
    #       - '**/*.js'
deploy:
  kubectl:
    manifests:
      - ./k8s_dev/bcc-agent-service-account.yaml
      - ./k8s_dev/bcc-agent-cluster-role-binding.yaml
      - ./k8s_dev/bcc-db-cluster-ip.yaml
      - ./k8s_dev/bcc-db-secret.yaml
      - ./k8s_dev/bcc-db-pvc.yaml
      - ./k8s_dev/bcc-db-deployment.yaml
      - ./k8s_dev/bcc-cache-cluster-ip.yaml
      - ./k8s_dev/bcc-cache-deployment.yaml

      - ./k8s_dev/bcc-api-server-cluster-ip.yaml
      - ./k8s_dev/bcc-api-server-deployment.yaml
      # - ./k8s_dev/deployment-job-worker.yaml
      # - ./k8s_dev/ingress.yaml
      # - ./k8s_dev/k8s/deployment-testdrivechain.yaml

