apiVersion: skaffold/v1beta13
kind: Config
metadata:
  name: bc-cloud
build:
  local:
    push: false
  artifacts:
    - image: bcc/api-server
      context: ./bcc-api-server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
    - image: bcc/job-worker
      context: ./bcc-job-worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
    # - image: bcc/web-client
    #   context: ./bcc-web-client
    #   docker:
    #     dockerfile: Dockerfile.dev
    #   sync:
    #     infer:
    #       - '**/*.js'
deploy:
  kubectl:
    manifests:
      - ./k8s/cluster-role-binding-job-worker.yaml
      - ./k8s/service-account-job-worker.yaml
      - ./k8s/cluster-ip-redis.yaml
      - ./k8s/deployment-redis.yaml
      - ./k8s/cluster-ip-api-server.yaml
      - ./k8s/deployment-api-server.yaml
      - ./k8s/deployment-job-worker.yaml
      # - ./k8s/cluster-ip-web-client.yaml
      # - ./k8s/deployment-web-client.yaml
      - ./k8s/ingress.yaml
      # - ./k8s/k8s/deployment-testdrivechain.yaml

