apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcc-api-gate-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      component: bcc-api-gate
  template:
    metadata:
      labels:
        component: bcc-api-gate
    spec:
      serviceAccountName: bcc-agent
      containers:
        - name: api-gate
          image: bsfans/bcc-api-gate
          ports:
            - containerPort: 5000
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bcc-db-credential
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bcc-db-credential
                  key: password
