apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api-server
  template:
    metadata:
      labels:
        component: api-server
    spec:
      serviceAccountName: job-worker
      initContainers:
        - name: check-redis
          image: redis
          command: [
            'sh',
            '-c',
            'until redis-cli -h redis -p 6379 ping; do echo waiting...; sleep 1; done;'
          ]
      containers:
        - name: api-server
          image: bcc/api-server
          ports:
            - containerPort: 5000
