apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcc-cache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: bcc-cache
  template:
    metadata:
      labels:
        component: bcc-cache
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379

  