apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcc-transaction-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: bcc-transaction-gate
  template:
    metadata:
      labels:
        component: bcc-transaction-gate
    spec:
      serviceAccountName: bcc-agent
      containers:
        - name: transaction-gate
          image: bcc/transaction-gate
          ports:
            - containerPort: 5000
          env:
              - name: DB_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: bcc-db-credential
                    key: username
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: bcc-db-credential
                    key: password
