apiVersion: skaffold/v1beta13
kind: Config
metadata:
  name: bc-cloud
build:
  local:
    push: false
  artifacts:
    - image: bcc/api-gate
      context: ../bcc-api-gate
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
    - image: bcc/db-gate
      context: ../bcc-db-gate
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
    - image: bcc/transaction-gate
      context: ../bcc-transaction-gate
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
    - image: bcc/agent
      context: ../bcc-agent
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
    - image: bcc/web-ui
      context: ../bcc-web-ui
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
deploy:
  kubectl:
    manifests:
      - ./bcc-web-ui-cluster-ip.yaml
      - ./bcc-web-ui-deployment.yaml
      - ./bcc-db-gate-cluster-ip.yaml
      - ./bcc-db-gate-deployment.yaml
      - ./bcc-api-gate-cluster-ip.yaml
      - ./bcc-api-gate-deployment.yaml
      - ./bcc-transaction-gate-cluster-ip.yaml
      - ./bcc-transaction-gate-deployment.yaml
      - ./bcc-agent-deployment.yaml
      - ./ingress.yaml


